= Requisitos
:allow-uri-read: 


Aprenda a implementar Postgres desde la https://bitnami.com/stack/postgresql/helm["Gráfico de Helm de BitNami"^]. Después de implementar Postgres en su clúster, puede registrar la aplicación con Astra Control.

Postgres es una aplicación validada para Astra.

* link:../concepts/validated-vs-standard.html#validated-apps["Descubre la diferencia entre una aplicación validada y una aplicación estándar en Astra Control"^].


Estas instrucciones se aplican tanto al Servicio de control Astra como al Centro de control Astra.


NOTE: Las aplicaciones puestas en marcha desde Google Marketplace no se han validado. Algunos usuarios reportan problemas con descubrimiento y/o copia de seguridad con las implementaciones de Google Marketplace de Postgres, MariaDB y MySQL.



== Requisitos

* Un clúster que se ha agregado a Astra Control.
+

NOTE: En Astra Control Center, puede agregar primero el clúster a Astra Control Center o agregar primero la aplicación.

* Versiones actualizadas de Helm (versión 3.2+) y Kubectl instaladas en una máquina local con el kubeconfig adecuado para el cluster




== Instalar Postgres

Dos notas importantes sobre este proceso:

* Debe implementar la aplicación después de agregar el clúster al servicio de control de Astra, no antes. Astra Control Center aceptará aplicaciones antes o después de que se agregue el clúster a Astra Control Center.
* Debe desplegar el gráfico Helm en un espacio de nombres distinto del predeterminado.


.Pasos
. Agregue el tipo de gráfico BitNami:
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. Desplegar Postgres con el comando:
+
[listing]
----
helm install <name> bitnami/postgresql -–namespace <namespace> --create-namespace
–-set global.storageClass=<storage_class_name>
----
+

NOTE: Si se cambia el tamaño del volumen, utilice las unidades Kibibyte (Ki), Mebibyte (mi) o Gibibyte (Gi).

+
Debe definir la clase de almacenamiento solo en estas situaciones:

+
** Está utilizando Astra Control Service y no desea utilizar la clase de almacenamiento predeterminada.
** Está utilizando Astra Control Center y todavía no ha importado el clúster a Astra Control Center. O bien, ha importado el clúster pero no desea utilizar la clase de almacenamiento predeterminada.




.Resultado
De este modo se realiza lo siguiente:

* Crea un espacio de nombres.
* Implementa Postgres en el espacio de nombres.


Una vez que las POD estén en línea, puede gestionar la aplicación con Astra Control. Astra Control permite gestionar una aplicación a nivel de espacio de nombres o mediante una etiqueta de timón.
